#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 482524-web-01 100.26.18.247:80 check
    server 482524-web-02 54.144.158.59:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
