#!/usr/bin/env bash
# Install your load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend estebanweb
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 482524-web-01 54.174.84.242:80 check
    server 482524-web-02 	52.91.153.21:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
