#!/usr/bin/env bash
# This script displays 1 
# 2 to infinity and beyond indefinitely
# 3 With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while true; do
    echo "to infinity and beyond"
    sleep 2
done
